name: Publish Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  publish:
    runs-on: React

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # ---- DOCKER LOGIN ----
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # ---- BUILD DOCKER IMAGE ----
      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/myapp:${{ github.sha }} .

      # ---- PUSH DOCKER IMAGE ----
      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/myapp:${{ github.sha }}

      # ---- CREATE GITHUB RELEASE ----
      - name: Create Release Tag
        id: tag_step
        run: |
          TAG=v-${{ github.sha }}
          echo "TAG=$TAG" >> $GITHUB_ENV
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.TAG }}
          name: "Release ${{ env.TAG }}"
          body: "Automated release created from publish pipeline."
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PERSONAL_TOKEN }}
